#端口
server:
  port: 8091

#spring相关
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    #database-platform: org.hibernate.dialect.MySQL8InnoDBDialect

  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qiuhen
    type: com.zaxxer.hikari.HikariDataSource






#配置日志
logging:
  #配置日志文件路径
  level:
    com.login.demo: debug #不同目录下的日志可配置不同级别
    org.springfromework.web: info
    org.hibernate: error
  #采用绝对路径方式将日志文件输出到【/Users/wang/Downloads/myspringboot.log】
  #file: /Users/wang/Downloads/myspringboot.log
  file:
    name: log/myspringboot.log
